// src/components/Comment.vue
<template>
<div>
	<div class="giscus"></div>
	<component :is="'script'"
		src="https://giscus.app/client.js"
		:data-repo="config.comment.repository"
		:data-repo-id="config.comment.repoId"
		:data-category="config.comment.category"
		:data-category-id="config.comment.categoryId"
		data-mapping="specific"
		:data-term="title"
		data-reaction-enabled="1"
		data-emit-metadata="0"
		data-theme="light"
		crossorigin="anonymous"
		async
	></component>
</div>
</template>

<script>
import config from '@root/config.json';

export default {
	props: {
		title: String,
	},

	data() {
		return {
			config,
		};
	},
};
</script>

<style lang="scss" scoped>
.giscus {
	@apply mb-4;
}
</style>

// src/components/Comment/index.tsx
import { comment } from '@root/config';
import { HTMLAttributes } from 'react';

import styles from './style.module.scss';

export const Comment = ({ title, className }: HTMLAttributes<{ title: string }>) => {
  if (!title) return;

  return (
    <>
      <div className={`${className} ${styles.giscus}`}></div>
      <script
        async
        src="https://giscus.app/client.js"
        data-repo={comment.repository}
        data-repo-id={comment.repoId}
        data-category={comment.category}
        data-category-id={comment.categoryId}
        data-mapping="specific"
        data-term={title}
        data-reaction-enabled="1"
        data-emit-metadata="0"
        data-theme="light"
        crossOrigin="anonymous"
      />
    </>
  );
};
