// src/pages/Archive.tsx
import { useEffect, useState } from 'react';
import { PostList } from '@src/components/PostList';
import { Post } from '@src/types/Post';
import { fetchPosts } from '@src/api';
import { createCommonMeta, createOpengraphMeta, createTwitterMeta } from '@src/utils/meta';
import { social, blogName, name, description, host } from '@root/config';

export const Archive = () => {
  const [posts, setPosts] = useState<Post[]>([]);

  useEffect(() => {
    fetchPosts().then((data) => {
      setPosts(data);

      const gravatar = `https://www.gravatar.com/avatar/${social.gravatar}`;

      const common = createCommonMeta({
        title: blogName,
        author: name,
        description: description,
      });
      const opengraph = createOpengraphMeta({
        siteName: blogName,
        type: 'website',
        url: host,
        title: blogName,
        description: description,
        image: gravatar,
      });
      const twitter = createTwitterMeta({
        card: 'summary',
        site: `@${social.twitter}`,
        title: blogName,
        description: description,
        image: gravatar,
      });

      document.head.append(common, opengraph, twitter);
    });
  }, []);

  return (
    <PostList posts={posts} title="Archive" />
  );
};

// src/pages/Archive.vue
<template>
<post-list :posts="posts">Archive</post-list>
<teleport to="head">
	<page-meta :meta="meta"></page-meta>
</teleport>
</template>

<script>
import PostList from '@src/components/PostList.vue';
import PageMeta from '@src/components/PageMeta.vue';

import { mapState, mapMutations, mapActions } from 'vuex';

import { social, blogName, name, description, host } from '@root/config';

export default {
	components: {
		PostList,
		PageMeta,
	},

	computed: {
		...mapState(['posts', 'meta']),
	},

	methods: {
		...mapMutations(['setMeta']),
		...mapActions(['loadPosts']),
	},

	async created() {
		await this.loadPosts();

		const gravatar = `https://www.gravatar.com/avatar/${social.gravatar}`;
		this.setMeta({
			title: `Archive - ${blogName}`,
			author: name,
			description: description,

			opengraph: {
				type: 'website',
				url: host,
				title: blogName,
				description: description,
				image: gravatar,
			},

			twitter: {
				card: 'summary',
				site: `@${social.twitter}`,
				title: blogName,
				description: description,
				image: gravatar,
			},
		});
	},
};
</script>
