// src/components/Home.vue
<template lang="pug">
fragment
    recent-posts
</template>

<script>
import Vue from 'vue';
import { Plugin } from 'vue-fragment';

Vue.use(Plugin);

import RecentPosts from './RecentPosts.vue';

import config from '@root/config.json';

export default {
    components: {
        RecentPosts,
    },

    metaInfo() {
        const gravatar = `https://www.gravatar.com/avatar/${config.links.gravatar}`;

        return {
            title: config.blogName,
            meta: [
                { name: 'author', content: config.name },
                { name: 'description', content: config.description },
                
                { property: 'og:type', content: 'website' },
                { property: 'og:url', content: config.host },
                { property: 'og:title', content: config.blogName },
                { property: 'og:description', content: config.description },
                { property: 'og:image', content: gravatar },
                
                { name: 'twitter:card', content: 'summary' },
                { name: 'twitter:site', content: `@${config.links.twitter}` },
                { name: 'twitter:title', content: config.blogName },
                { name: 'twitter:description', content: config.description },
                { name: 'twitter:image', content: gravatar },
            ],
        };
    },
}
</script>

// src/pages/Home.tsx
import { useAtomValue } from 'jotai';
import { Helmet } from 'react-helmet-async';
import { PostList } from '../components/PostList';
import { config } from '../config';
import { postsAtom } from '../stores';

export const Home = () => {
  const gravatar = `https://www.gravatar.com/avatar/${config.gravatar}`;
  const posts = useAtomValue(postsAtom);

  return (
    <>
      <Helmet>
        <title>{config.blogName}</title>
        <meta name="author" content={config.author} />
        <meta name="description" content={config.description} />

        <meta property="og:site_name" content={config.blogName} />
        <meta property="og:type" content="website" />
        <meta property="og:url" content={config.host} />
        <meta property="og:title" content={config.blogName} />
        <meta property="og:description" content={config.description} />
        <meta property="og:image" content={gravatar} />
      </Helmet>
      <PostList posts={posts}>Recent Posts</PostList>
    </>
  );
};
