// src/pages/Home.tsx
import { useEffect, useState } from 'react';
import { PostList } from '@src/components/PostList';
import { Post } from '@src/types/Post';
import { fetchPosts } from '@src/api';
import { createCommonMeta, createOpengraphMeta, createTwitterMeta } from '@src/utils/meta';
import { social, blogName, name, description, host } from '@root/config';

export const HomePage = () => {
  const [posts, setPosts] = useState<Post[]>([]);

  useEffect(() => {
    fetchPosts({ length: 5 }).then((data) => {
      setPosts(data);

      const gravatar = `https://www.gravatar.com/avatar/${social.gravatar}`;

      const common = createCommonMeta({
        title: blogName,
        author: name,
        description: description,
      });
      const opengraph = createOpengraphMeta({
        siteName: blogName,
        type: 'website',
        url: host,
        title: blogName,
        description: description,
        image: gravatar,
      });
      const twitter = createTwitterMeta({
        card: 'summary',
        site: `@${social.twitter}`,
        title: blogName,
        description: description,
        image: gravatar,
      });

      document.head.append(common, opengraph, twitter);
    });
  }, []);

  return (
    <PostList posts={posts} title="Recent Posts" />
  );
};

// src/pages/Home.vue
<template>
<post-list :posts="posts">Recent Posts</post-list>
</template>

<script>
import PostList from '@src/components/PostList.vue';

import { mapState, mapActions } from 'vuex';

import config from '@root/config.json';

export default {
	components: {
		PostList,
	},

	computed: {
		...mapState(['posts']),
	},

	methods: {
		...mapActions(['loadPosts']),
	},

	async serverPrefetch() {
		await this.loadPosts({
			length: 5,
		});

		// const gravatar = `https://www.gravatar.com/avatar/${config.links.gravatar}`;
		// this.$ssrContext.title = config.blogName;
		// this.$ssrContext.meta = {
		// 	author: config.name,
		// 	description: config.description,

		// 	opengraph: {
		// 		type: 'website',
		// 		url: config.host,
		// 		title: config.blogName,
		// 		description: config.description,
		// 		image: gravatar,
		// 	},

		// 	twitter: {
		// 		card: 'summary',
		// 		site: `@${config.links.twitter}`,
		// 		title: config.blogName,
		// 		description: config.description,
		// 		image: gravatar,
		// 	},
		// };
	},
};
</script>
