// src/pages/Post.vue
<template lang="pug">
.post
    h1.post__title {{title}}
    .post__tags
        span.sr-only tags
        tags(:tags="tags")
    .post__published
        span.sr-only published
        time {{ published }}
    article.post__article(v-html="html")
    comment.post__comment(v-if="title" :title="title")
</template>

<script>
import format from 'date-fns/format';

import config from '@root/config.json';

import Tags from '@src/components/Tags.vue';
import Comment from '@src/components/Comment.vue';

import axios from 'axios';

export default {
	components: {
		Tags,
		Comment,
	},

	data() {
		return {
			title: '',
			tags: [],
			published: null,

			html: '',
		};
	},

	metaInfo() {
		const gravatar = `https://www.gravatar.com/avatar/${config.links.gravatar}`;
		const desc = this.html.replace(/(<([^>]+)>)/gi, '').slice(0, 55);

		return {
			title: `${this.title} - ${config.blogName}`,
			meta: [
				{ name: 'author', content: config.name },
				{ name: 'description', content: desc },

				{ property: 'og:type', content: 'article' },
				{ property: 'og:url', content: location.href },
				{ property: 'og:title', content: this.title },
				{ property: 'og:description', content: desc },
				{ property: 'og:image', content: gravatar },

				{ name: 'twitter:card', content: 'summary' },
				{ name: 'twitter:site', content: `@${config.links.twitter}` },
				{ name: 'twitter:title', content: this.title },
				{ name: 'twitter:description', content: desc },
				{ name: 'twitter:image', content: gravatar },
			],
		};
	},

	async created() {
		const post = (await axios.get(`/api${location.pathname}`)).data;

		this.title = post.meta.title;
		this.tags = post.meta.tags;
		this.published = format(new Date(post.meta.published), 'yyyy-MM-dd');

		this.html = post.content;
	},
};
</script>

<style lang="scss" scoped>
@import 'styles/markdown.scss';

.post {
	&__title {
		@apply text-4xl;
	}

	&__tags {
		@apply mt-2;
	}

	&__published {
		@apply border-b;
		@apply border-gray-300;
		@apply pb-2;
		@apply mb-6;
	}

	&__article {
		@apply mb-6;

		::v-deep {
			@include markdown;
		}
	}
}
</style>

// src/pages/Post.tsx
import { useAtomValue } from 'jotai';
import { Helmet } from 'react-helmet-async';
import { useParams } from 'react-router';
import { Comment } from '../components/Comment';
import { TagList } from '../components/TagList';
import { config } from '../config';
import { postAtom } from '../stores';
import { formatDate } from '../utils/format';

import style from './Post.module.scss';

export const Post = () => {
  const { title } = useParams();
  const post = useAtomValue(postAtom);
  const commitLog = `https://github.com/${config.history.org}/${config.history.repo}/commits/develop/posts/${title}`;
  const gravatar = `https://www.gravatar.com/avatar/${config.gravatar}`;
  const desc = post.content
    .replace(/(<([^>]+)>)/gi, '')
    .slice(0, 55)
    .trim();

  if (!post) return null;

  return (
    <>
      <Helmet>
        <title>
          {post.meta.title} - {config.blogName}
        </title>
        <meta name="author" content={config.author} />
        <meta name="description" content={config.description} />

        <meta property="og:site_name" content={config.blogName} />
        <meta property="og:type" content="article" />
        <meta property="og:url" content={`${config.host}/post/${title}`} />
        <meta property="og:title" content={post.meta.title} />
        <meta property="og:description" content={desc} />
        <meta property="og:image" content={gravatar} />
      </Helmet>
      <div className={style.post}>
        <div className={style.post__meta}>
          <h1 className={style.post__title}>{post.meta.title}</h1>
          <div className={style.post__tags}>
            <span className="sr-only">tags</span>
            <TagList tags={post.meta.tags || []} />
          </div>
          <div className={style.post__updated}>
            <span>Last Updated: </span>
            <a target="_blank" rel="noreferrer" href={commitLog}>
              <time>{formatDate(new Date(post.meta.updated))}</time>
            </a>
          </div>
        </div>
        <article
          className={style.post__article}
          // biome-ignore lint/security/noDangerouslySetInnerHtml:
          dangerouslySetInnerHTML={{ __html: post.content }}
        />
        <Comment title={post.meta.title} />
      </div>
    </>
  );
};
