// .old/components/Post.vue
<template lang="pug">
.article
    div.category
        span.sr-only category
        router-link(:to="`/category/${category}`") /{{category}}
    h1.title {{title}}
    div.published
        span.sr-only published
        time {{ published }}
    article(v-html="html")
    div
        span.sr-only tags
        ul.tags
            tag(v-for="tag in tags" :name="tag")
        #disqus_thread.comment
</template>

<script>
import format from 'date-fns/format';

import config from '@root/config.json';

import Tag from './Tag.vue';

export default {
    components: {
        Tag,
    },

    data() {
        return {
            title: '',
            category: '',
            tags: [],
            published: null,

            html: '',
        };
    },

    metaInfo() {
        const gravatar = `https://www.gravatar.com/avatar/${config.links.gravatar}`;
        const desc = this.html.replace(/(<([^>]+)>)/ig,"").slice(0, 55);

        return {
            title: `${this.title} - ${config.blogName}`,
            meta: [
                { name: 'author', content: config.name },
                { name: 'description', content: desc },

                { property: 'og:type', content: 'article' },
                { property: 'og:url', content: location.href },
                { property: 'og:title', content: this.title },
                { property: 'og:description', content: desc },
                { property: 'og:image', content: gravatar },

                { name: 'twitter:card', content: 'summary' },
                { name: 'twitter:site', content: `@${config.links.twitter}` },
                { name: 'twitter:title', content: this.title },
                { name: 'twitter:description', content: desc },
                { name: 'twitter:image', content: gravatar },
            ],
        };
    },

    methods: {
        loadComment() {
            const disqus_config = function () {
                this.page.url = `${config.host}${location.pathname}`;
                this.page.identifier = location.pathname;
            };
            (function() {
                const d = document, s = d.createElement('script');
                s.src = config.links.disqus;
                s.setAttribute('data-timestamp', +new Date());
                (d.head || d.body).appendChild(s);
            })();
        },
    },

    created() {
        const context = require.context('@root/contents/posts?with-html', true, /\.md$/);
        const data = context(`./${this.$route.params.path.replace(/\.html$/, '.md')}`);

        this.title = data.title;
        this.category = data.category;
        this.tags = data.tags;
        this.published = format(new Date(data.published || null), 'yyyy-MM-dd');

        this.html = data.html;

        if (!IS_DEV) {
            this.loadComment();
        }
    },
}
</script>

// src/pages/Post/index.tsx
import { Comment } from '@src/components/Comment';
import { Tag } from '@src/components/Tag';
import { Post } from '@src/types/Post';
import { format } from 'date-fns';

import { comment, blogName, social, name, description, host } from '@root/config';
import { createCommonMeta, createOpengraphMeta, createTwitterMeta } from '@src/utils/meta';

import styles from './style.module.scss';

// FIXME: optional
export const PostPage = ({ post }: { post?: Post }) => {
  if (!post || !post.meta) return null;

  // FIXME: optional
  const published = format(post.meta.published, 'yyyy-MM-dd');
  const commitLog = `https://github.com/${comment.repository}/commits/develop/posts/${post.meta.title}`;

  // FIXME: useEffect
  const onLoad = () => {
    const gravatar = `https://www.gravatar.com/avatar/${social.gravatar}`;
    const title = post.meta.title;
    const siteName = `${title} - ${blogName}`;
    const desc = post.content?.replace(/(<([^>]+)>)/gi, '').slice(0, 55);

    const common = createCommonMeta({
      title: siteName,
      author: name,
      description: description,
    });
    const opengraph = createOpengraphMeta({
      siteName,
      type: 'article',
      url: `${host}/post/${post.meta.title}/index.html`,
      title,
      description: desc,
      image: gravatar,
    });
    const twitter = createTwitterMeta({
      card: 'summary',
      site: `@${social.twitter}`,
      title,
      description: desc,
      image: gravatar,
    });

    document.head.append(common, opengraph, twitter);
  };

  return (
    <div className={styles.post} onLoad={onLoad}>
      <div className={styles.post__meta}>
        <h1 className={styles.post__title}>{post.meta.title}</h1>
        <div className={styles.post__tags}>
          <span className="sr-only">tags</span>
          <Tag tags={post.meta.tags} />
        </div>
        <div className={styles.post__published}>
          <span className="sr-only">published</span>
          <a target="_blank" href={commitLog}>
            <time>{published}</time>
          </a>
        </div>
      </div>
      <article className={styles.post__article} dangerouslySetInnerHTML={{__html: post.content}}></article>
      <Comment title={post.meta.title} />
    </div>
  );
};
