// src/components/Comment.tsx
import { config } from '../config';
import { useScript } from '../hooks/useScript';

import './Comment.scss';

export const Comment = ({ title }: { title: string }) => {
  useScript('https://giscus.app/client.js', {
    async: true,
    crossOrigin: 'anonymous',
    data: {
      repo: config.giscus.repository,
      'repo-id': config.giscus.repoId,
      category: config.giscus.category,
      'category-id': config.giscus.categoryId,
      mapping: 'specific',
      term: title,
      'reaction-enabled': 1,
      'emit-metadata': 0,
      theme: 'light',
    },
  });

  return <div className="giscus" />;
};

// src/components/Comment.vue
<template>
<div>
	<div class="giscus"></div>
	<component :is="'script'"
		src="https://giscus.app/client.js"
		:data-repo="config.comment.repository"
		:data-repo-id="config.comment.repoId"
		:data-category="config.comment.category"
		:data-category-id="config.comment.categoryId"
		data-mapping="specific"
		:data-term="title"
		data-reaction-enabled="1"
		data-emit-metadata="0"
		data-theme="light"
		crossorigin="anonymous"
		async
	></component>
</div>
</template>

<script>
import config from '@root/config.json';

export default {
	props: {
		title: String,
	},

	data() {
		return {
			config,
		};
	},
};
</script>

<style lang="scss" scoped>
.giscus {
	@apply mb-4;
}
</style>
