// src/components/PostItem.tsx
import style from './PostItem.module.scss';
import { TagList } from './TagList';

export type Post = {
  meta: {
    title: string;
    tags?: string[];
  };
  content: string;
  url: string;
};

const MAX_LENGTH = 100;

export const PostItem = ({ post }: { post: Post }) => {
  const desc =
    post.content.length > MAX_LENGTH
      ? `${post.content.slice(0, MAX_LENGTH)}...`
      : post.content;

  return (
    <li className={style['post-item']}>
      <a href={post.url}>
        <h3 className={style['post-item__title']}>{post.meta.title}</h3>
        <p className={style['post-item__desc']}>{desc}</p>
      </a>
      {post.meta.tags && post.meta.tags.length > 0 && (
        <dl className={style['post-item__meta-info']}>
          <dt className="sr-only">tags</dt>
          <dd className={style['post-item__tags']}>
            <TagList tags={post.meta.tags} />
          </dd>
        </dl>
      )}
    </li>
  );
};

// src/components/PostItem.vue
<template>
<li class="post-item">
	<a :href="post.url">
		<h3 class="post-item__title">{{ post.meta.title }}</h3>
		<p class="post-item__desc">{{ desc }}</p>
	</a>
	<dl class="post-item__meta-info">
		<dt class="sr-only">tags</dt>
		<dd class="post-item__tags">
			<tags :tags="post.meta.tags"></tags>
		</dd>
	</dl>
</li>
</template>

<script>
import Tags from './Tags.vue';

export default {
	components: { Tags },

	props: ['post'],

	computed: {
		desc() {
			const maxLength = 100;
			const desc = this.post.content;

			return desc.length > maxLength ? `${desc.slice(0, maxLength)}...` : desc;
		},
	},
}
</script>

<style lang="scss" scoped>
.post-item {
	@apply w-full;
	@apply py-4;
	@apply border-b;

	&:last-child {
		@apply border-b-0;
	}

	&__title {
		@apply text-xl;
	}

	&__desc {
		@apply pt-1;
		@apply font-light;
	}

	&__meta-info {
		@apply flex;
		@apply flex-row;
		@apply pt-1;
	}

	&__tags {
		@apply mr-3;
	}
}
</style>
