// src/App.tsx
import { useEffect } from 'react';
import { createBrowserRouter, RouterProvider, Outlet } from 'react-router-dom';
import { Header } from '@src/components/Header';

import styles from './style.module.scss';
import { runGoogleAnalytics } from '@src/utils/googleAnalytics';
import { HomePage } from '@src/pages/Home';
import { PostPage } from '@src/pages/Post';
import { Archive } from '@src/pages/Archive';
import { Tag } from './pages/Tag';
import { Search } from './pages/Search';

const router = createBrowserRouter([
  {
    element: (
      <div className={styles.container}>
        <Header />
        <main>
          <Outlet />
        </main>
      </div>
    ),
    children: [
      {
        path: '/',
        element: <HomePage />,
      },
      {
        path: '/post/:title/index.html',
        element: <PostPage />,
      },
      {
        path: '/archive/index.html',
        element: <Archive />,
      },
      {
        path: '/tag/:tag/index.html',
        element: <Tag />,
      },
      {
        path: '/search/index.html',
        element: <Search />,
      },
    ],
  },
]);

export const App = () => {
  useEffect(() => {
    runGoogleAnalytics();
  }, []);

  return (
    <RouterProvider router={router} />
  );
};

// src/App.vue
<template>
<div id="app" class="container">
	<blog-header></blog-header>
    <main>
		<components :is="currentComponent"></components>
	</main>
    <footer></footer>
</div>
</template>

<script>
import BlogHeader from './components/BlogHeader.vue';

import Home from './pages/Home.vue';
import Tag from './pages/Tag.vue';
import Archive from './pages/Archive.vue';
import Post from './pages/Post.vue';

export default {
	components: {
		BlogHeader,

		Home, Tag, Archive, Post,
	},

	data() {
		return {
			currentComponent: '',
		};
	},

	mounted() {
		if (location.pathname === '/' || location.pathname === '/index.html') {
			this.currentComponent = 'Home';
		} else if (/^\/archive/.test(location.pathname)) {
			this.currentComponent = 'Archive';
		} else if (/^\/tag\//.test(location.pathname)) {
			this.currentComponent = 'Tag';
		} else if (/^\/post\//.test(location.pathname)) {
			this.currentComponent = 'Post';
		}
	},
};
</script>
